- src/commands/run.js
Avoids the issues we've been seeing with people having their NODE_ENV set to something other than `development`
> check for non-dev environment in `run`, bail with message

- src/commands/buildCommands/config/webpack/_babelrc.js
https://meetup.atlassian.net/browse/WP-351
---
these messages can no longer be seen as mwp-cli no longer displays webpack output but it doesn't hurt should someone want to look at them later.
https://stackoverflow.com/a/29857361
> remove deoptimized styling msgs

- src/commands/run.js
- src/commands/runScripts/start-dev.js
the locale args weren't being passed to `startServer` in `start-dev.js`. This PR fixes that.
When mup-web and pro-web are updated, `yarn start -- --locales en-US fr-FR` will run the server with multiple language support
> Pass locale args through `run` builders/runners

- src/commands/buildCommands/config/webpack/browserAppConfig.js
- src/commands/buildCommands/config/webpack/serverAppConfig.js
`eval` was providing a source map that contained the transpiled code
`cheap-module-source-map` creates a source map that shows the original code, and it appears to be approximately as fast as `eval` - in mup-web `yarn start` takes about 10 seconds with `eval`, and 11 seconds with `cheap-module-source-map`.
I've also removed the `devtool` config for `serverAppMap` because we don't have a use case server app source maps currently, and it makes the server build slightly slower than having no `devtool` at all.
Before:
After:
> Proper source maps in dev

- src/config/README.md
- src/config/index.js
- src/config/server/index.js
- src/config/server/index.test.js
- src/config/server/util.js
This PR documents the config that is currently managed by mwp-cli, although it is expected to be spun off into its own package in the near future.
In addition, the application server config script has been moved over from MWP - although MWP is the only consumer of that config, managing it here helps keep the overall system internally consistent - CONFIG IS MANAGED IN A SINGLE PLACE.
The server config script has been converted to Node-friendly ES6 (i.e. no ES6 `import`/`export`), and some helper functions/constants have been moved to a separate `util.js` script. Otherwise, the functionality is untouched so it probably doesn't need in-depth review.
> WP 425 config docs + server config consolidation

- docs/run.md
- src/commands/run.js
Enabling request logging in WDS is a little indirect because you have to set an environment variable that the Express server reads to determine whether/what to log. I decided that enabling this logging with a CLI option was probably the best opt-in mechanism, and the code change is pretty minor. Not sure if we should use another channel to let people know that this option exists - I suspect it will mostly go unnoticed.
> WP 454 Webpack Dev Server asset server logging

- src/config/index.js
since the server config module validates as soon as it's imported, it will fail in an environment that only provides build-time environment variables, e.g. Travis
> make the server config a getter

- src/config/README.md
- src/config/server/index.test.js
- src/config/webpack/browserAppConfig.js
As per: https://meetup.atlassian.net/browse/MUP-15692
This PR is to add support for configuring INTERCOM_APP_ID, needed to support the 3rd Party service Intercom that Meetup sometimes uses for messaging users, onboarding, and support campaigns.
> added support for INTERCOM_APP_ID config

- src/commands/txCommands/pushNewContent.js
- src/commands/txCommands/pushTxMaster.js
- src/commands/txCommands/util/index.js
I noticed that pushing translated content to master wasn't working as it should. The primary culprit is the change I made in a failed effort to support translation changes in transifex. After thinking it over, I decided that it would be better to have a simpler system where content flows only in one direction than to support a wider set of use cases. One of the larger failing of the tx integration is that it can be difficult to reason about. This will make it significantly simpler.
Rather than revert the change set from August, I decided to only change what was necessary. I also kept most of the logging that helped me debug what was wrong.
> fix push to master - push everything , every launch

- CHANGELOG.md
- Makefile
- package.json
- src/config/webpack/rules.js
eslint complains too much about things I don't care about early in the dev process
> Disable eslint webpack loader

- CHANGELOG.md
- Makefile
- src/commands/ghCommands/status.js
This should allow us to set PR status for PRs that come from a third-party fork (e.g. the AgilityIO PRs). Travis will supply the downstream repo name as `owner/repo` in the `TRAVIS_PULL_REQUEST_SLUG` env variable during a build, which can then be passed to the script invocation as a `GITHUB_REPO` env var or `--repo` CLI option
> allow owner/repo to be supplied to 'repo' arg

- docs/tx.md
- src/commands/txCommands/pullAll.js
- src/commands/txCommands/util/gitHelpers.js
- src/commands/txCommands/util/index.js
The translation flow currently does not allow for corrections to copy without developer work. Let's change that.
1. Add a new resource to the mup-web project ("main" or something of that sort) that includes all translations in the project.
2. Every time we pull translations, if "main" exists, then pull and update all translations in mup-web. Then pull all the rest of the resources.
3. Every time we push to master, also update and sync main to match the current state of mup-web.
4. ????
5. Profit!!!!!!
1. Modify the `pullAll` mwp-cli command to include a `all_translations` resource, but have it download first so that changes in other branches are applied on top of it
> WP-624 adjusting pull all for main

- CHANGELOG.md
- Makefile
- src/cli.js
- src/commands/buildCommands/browser.js
- src/commands/buildCommands/trn.js
In order to move toward allowing MWP applications to support all languages in a single bundle, we need to update the format of the transpiled TRN JSON so that translations for multiple languages can co-exist.
This branch updates the format from this:
```js
{ "trn.key.one": "stuff that is translated" }
```
to this:
```js
{
"en-US": { "trn.key.one": "stuff that is translated" }
}
```
it also adds support for a `config.combineLanguages` flag in an applications `package.json` that will write combined-language source JSON that looks like this:
```js
{
"en-US": { "trn.key.one": "stuff that is translated" },
"fr-FR": { "trn.key.one": "des choses qui sont traduites" },
...
}
```
Follow-on updates to MWP are needed in order to correctly parse the TRN source - this is a breaking change for that …
> New format for transpiled TRN source JSON

- CHANGELOG.md
- Makefile
- src/commands/buildCommands/server.js
- src/commands/buildCommands/trn.js
- src/commands/run.js
- src/commands/runScripts/_app-server.js
- src/commands/runScripts/_webpack-dev-server.js
- src/commands/runScripts/start-dev.js
- src/util/addLocalesOption.js
**Refactored** `build trn` and `run` will both bundle the app code so that a single bundle supports all languages _in dev_ - this makes for a very large app bundle, but that should be fine in dev and it avoids having to hassle with running the app with `--locales` options. In prod, `build trn` will work as usual.
**New feature** `build [server|browser]` will now write a single bundle supporting all languages if the calling application specifies `config.combineLanguages: true` in its `package.json`.
> WP 639 build combined lang bundle

- .yarnrc
- CHANGELOG.md
- Makefile
- README.md
- docs/time.md
- package.json
- src/commands/time.js
- yarn.lock
This CLI will allow us to track build timing data in New Relic Insights over time.
TODO
> CLI for recording start/stop times and tracking in New Relic Insights

- docs/deploy.md
- src/commands/deployCommands/create.js
- src/commands/deployUtils/apiMiddleware.js
- src/commands/deployUtils/versions.js
In order to use `deploy create` in pro-web, we need to be able to specify the source Docker image tag and pass in arbitrary additional environment variables specified by CLI options
> WP 652 new `deploy create` options: --image, --env

- src/commands/deployCommands/create.js
- src/commands/deployUtils/versions.js
This will allow the `deploy create` command to be configurable with the minimum instances, which will be used by the canary build to perform a very small (and hopefully fast) deployment of a single instance that will hand e2e tests
> add `--minInstances` deploy option

- src/commands/runScripts/start-dev.js
When I tested with the beta package this wasn't happening, but now in  mup-web seems like stats might be undefined, so adding a check:
```/Users/sadaf/git_repo/mup-web/node_modules/mwp-cli/src/commands/runScripts/start-dev.js:37
const info = stats.toJson();
^
TypeError: Cannot read property 'toJson' of undefined
at /Users/sadaf/git_repo/mup-web/node_modules/mwp-cli/src/commands/runScripts/start-dev.js:37:21
at ChildProcess.wdsProcess.on.message (/Users/sadaf/git_repo/mup-web/node_modules/mwp-cli/src/commands/runScripts/start-dev.js:113:3)
at ChildProcess.emit (events.js:180:13)
at emit (internal/child_process.js:783:12)```
> Update start-dev.js; check for stats

- package.json
- src/commands/buildCommands/configs/postCssLoaderConfig.js
- yarn.lock
This version of [postcss-css-variables](https://github.com/MadLittleMods/postcss-css-variables) adds an option called `preserveInjectedVariables`. When set to false, custom properties don't get injected with each style module. See example output below from `insetParagraph.module.scss` - a module used on the about page
Before `preserveInjectedVariables: false`:
After `preserveInjectedVariables: false`:
> Upgrade postcss variable plugin

- package.json
- yarn.lock
Need to upgrade webpack in order for mup-web storybook downgrade to `4.0.0.alpha-8` to work. 
Can't go back to non-alpha because we're on webpack 4.
> upgrade webpack

- CHANGELOG.md
- Makefile
- src/commands/buildCommands/trn.js
This PR updates `mope build trn` to write language-specific datepicker `locale` definition modules. These modules are similar to transifex translation data, but provide flatpickr `locale` data that can be passed into MWC `CalendarComponent`
**Followup** define a standard `<DatePicker />` component in mup-web that will automatically localize the datepicker based on the current user's `requestLanguage`
> add picker locale modules to `build trn` output

- src/commands/txCommands/push.js
- src/commands/txCommands/util/pushTxAllTranslations.js
- src/commands/txCommands/util/pushTxMaster.js
Jira ticket here:
https://meetup.atlassian.net/browse/WP-921
This problem has 2 parts:
1. Branches in PR: malformed trns silently fail the mope tx push command, which is called on PR branches
2. Branches merged to master: malformed trns throw an error but still succeeds the travis job that pushes trn keys
Because of both of these bugs, translations were broken for a few weeks because errors were being thrown, halting the translation upload process, but we were unaware this was happening because all checks and travis builds were succeeding.
What this PR does:
- Make sure errors are handled in `mope tx push`
- exit the process if it fails to push translations - if it's going to fail it should fail loudly otherwise we'll never know until it's too late. 
tested this with this mup-web PR: …
> add error handling function to `tx push`

- CHANGELOG.md
- Makefile
- README.md
- src/commands/deploy.js
- src/commands/deployCommands/delete.js
- src/commands/deployCommands/stop.js
`mope deploy stop` to stop a particular deployment (version) from serving in GAE
- frees CPU/instance resources
> WP 951 deploy stop

- src/commands/buildCommands/trn.js
https://meetup.atlassian.net/browse/OS-90
Locale is being sent to the CalendarComponent like so
According to the structure of the js object expected by CalendarComponent and Flatpickr's docs on using modules https://flatpickr.js.org/localization/#using-modules the json stored should look like the `default.${lang}` sub-object instead of the entire object.
It is now building the `trn` files as expected
> OS-90: Date picker calendar not localized

- src/commands/buildCommands/configs/vendorBundlesConfig.js
Shrink the hard-to-cache app bundle by moving js-joda to the easy-to-cache vendor bundle
> add js-joda, js-joda-timezone to vendor bundle

- src/commands/txCommands/pullAll.js
- src/commands/txCommands/util/index.js
A quick fix for the failing `pullAll` in the *-web pipelines: since the `tfx` functionality is now mainly accessed through `util/transifex`, I'm trying to minimize changes necessary by exposing the interface whole-sale through `util/index`.
> Make tfx interface available through the default module export

- CHANGELOG.md
- Makefile
- src/commands/buildCommands/configs/rules.js
- src/commands/buildCommands/trn.js
https://www.pivotaltracker.com/story/show/166855878
Feature update to correctly transpile TRN source content into TRN modules inside `src/trns/modules/...`. No consume changes required, although all packages importing TRNs will need to use the import path of `'trns/my-package-name/path/to/source';`
This is a blocker for https://github.com/meetup/mup-web/pull/6013
> feature: write package trns to package-prefixed modules dir

- src/commands/txCommands/util/index.js
- src/commands/txCommands/util/poFormatters.js
With the latest mwp-cli, we found errors in `pro-web` where a trn was being defined in a test file so the entire build error'd. 
To avoid this, let's go back to omit-ting story and test files from the trn src glob.
Reference, removed here: https://github.com/meetup/mwp-cli/commit/010d869c55041ba65da274fdcbb93d5a459abb05#diff-b7ed5127b5fcf4b7bfb5d049d728fc07L66
> Omit story and test files from trn src glob

- src/commands/txCommands/util/__snapshots__/poFormatters.test.js.snap
- src/commands/txCommands/util/poFormatters.js
Engineers can now avoid defining a `jira` property in the TRN message descriptors. Also, other `description` keys will be more clearly labeled in the PO objects/files
> Remove `jira` validation & stringify description object key-values

- CHANGELOG.md
- Makefile
- src/commands/buildCommands/configs/rules.js
- src/commands/bundleCommands/configs/rules.js
Using this cache directory appears to cut the build time in half (for `mope bundle ...`), from about 2 minutes to about 1 minute. It's sort of a small, but very easy optimization that should also help build speed in dev even when clearing the `node_modules` directory
> Add home-relative babel-loader cacheDirectory that can be re-used in CI

- src/commands/txCommands/util/__snapshots__/poFormatters.test.js.snap
- src/commands/txCommands/util/poFormatters.js
- src/commands/txCommands/util/poFormatters.test.js
for https://www.pivotaltracker.com/story/show/170032992, followup from Slack mention of redundant/messy automatedTRN PRs: https://meetuphq.slack.com/archives/C3MD0EV7V/p1573500476009700
This will make the PO file output more deterministic (sorted by `msgid`) so that we can avoid redundant automated TRN builds and see specific changes more clearly.
> Sort the PO keys before writing PO file

- package.json
- src/commands/txCommands/pullAll.js
- src/commands/txCommands/push.js
- yarn.lock
Fixes: PIVOTAL-[170232239](https://www.pivotaltracker.com/story/show/170232239)
The recent update of `yargs` from `11.0.0` to `14.2.0` has broken `--commit` option of `mope tx pullAll` command - it started to be interpreted as `false`. As a result, mup-web's translation cron has began to fail, because it was no longer committing updated translation files.
This PR updates `yargs` to the latest version and ensures that each optional flag has an explicit type annotation. Local testing confirmed that this solves the issue with parsing of `--commit` option
> 170232239: yargs 14.2.0 -> 15.0.2

- src/commands/bundleCommands/pull.js
Fix MupWeb travis build crash on timeouts running "mope bundle pull --s3Bucket=mwp-mup-web-prod-app-build" with mwp-cli/src/commands/bundleCommands/pull.js:61	throw new Error(`Timeout - ${Math.floor(timeout / 1000)}sec`);
> Fix MupWeb travis build crash on timeout

- .github/workflows/ci.yml
Currently, the npm package publishing often failed, thus adding a retry action to save some manual clicks.
> ci: retry npm publish step

- package.json
- yarn.lock
Reverts meetup/mwp-cli#446
---
```
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: [object Object] is not a PostCSS plugin
at Processor.normalize (/home/travis/build/meetup/mup-web/node_modules/postcss-loader/node_modules/postcss/lib/processor.js:168:15)
at new Processor (/home/travis/build/meetup/mup-web/node_modules/postcss-loader/node_modules/postcss/lib/processor.js:52:25)
at postcss (/home/travis/build/meetup/mup-web/node_modules/postcss-loader/node_modules/postcss/lib/postcss.js:55:10)
at Promise.resolve.then.then (/home/travis/build/meetup/mup-web/node_modules/postcss-loader/src/index.js:140:12)
```
caused [container build issue](https://travis-ci.com/github/meetup/mup-web/jobs/511790219)
> Revert "chore(deps): bump postcss-css-variables from 0.13.0 to 0.18.0"

- CHANGELOG.md
- Makefile
- package.json
- src/commands/bundleCommands/trn.js
- src/commands/txCommands/pull.js
- src/commands/txCommands/pullAll.js
- src/commands/txCommands/push.js
- src/commands/txCommands/util/constants.js
- src/commands/txCommands/util/poFormatters.js
- src/commands/txCommands/util/transifexApi.js
- src/commands/txCommands/util/utilsV3.js
- yarn.lock
`mwp-cli tx` depends on deprecated Transifex API. Calls to these APIs and any scripts that depend on them will not work after Nov 30, 2022. So, cli needs to be updated.
Adds utilities to use transifex api v3 for pull, pullAll, push commands.
Introduces temporary `--v3` argument `--version3, --v3  Use Transifex v3 under the hood   [boolean] [default: false]` 
to specify that new utilities should be used.
It as well as all utilities depended on deprecated api will be deleted after testing new cli version on `mup-web` and `web-next`
> add utilities to use transifex api v3 for pull, pullAll, push commands

- .github/workflows/ci.yml
relates to https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
relates to https://github.com/meetup/meetup-web-platform/pull/974
> chore: deprecate `set-output` and update default branch
