meetup/mwp-cli

- src/cli.js
- src/commands/build.js
- src/commands/buildCommands/browser.js
- src/commands/buildCommands/server.js
- src/commands/buildCommands/vendor.js
- src/commands/run.js
- src/util/addLocalesOption.js
the locale arguments were being parsed for all commands, not just build commands
i also removed null builder functions.
> locales only for build command, cleanup

- .travis.yml
- package.json
- yarn.lock
https://meetup.atlassian.net/browse/WP-412
add coveralls coverage
> add coveralls

- CHANGELOG.md
- Makefile
- src/config/env.js
This is all that is needed to update the static path, but downstream will need to update static proxy settings for prod
> update default static path to mu_static

- src/commands/runScripts/start-dev.js
Simple logging update to provide compilation error output and a more accurate recommended fix (try `yarn start:full`)
> WP 401 print trn error

- CHANGELOG.md
- Makefile
- src/commands/txCommands/status.js
- src/commands/txCommands/util/index.js
- src/config/index.js
- src/config/localesSecondary.js
`mope tx status`
Displays two lists of resources  - incomplete, listing incomplete language and percentages, and complete. Accounts for 'secondary' languages such as en-AU and es-ES that do not determine completion.
There are some prettier formatting changes as well.
> resource status command

- src/config/webpack/browserAppConfig.js
- src/config/webpack/rules.js
- src/config/webpack/serverAppConfig.js
> Revert "Add img file-loader rule"

- CHANGELOG.md
- Makefile
- package.json
- src/config/webpack/browserAppConfig.js
- src/config/webpack/rules.js
- src/config/webpack/serverAppConfig.js
- yarn.lock
> Add file-loader and raw-loader rules

- src/config/locales.js
- src/config/localesSecondary.js
It's redirecting and breaking for actual russian users right now.
> Remove russian.

- CHANGELOG.md
- Makefile
- src/config/webpack/serverAppConfig.js
> add 'webfont' alias support

- src/config/locales.js
Just adding russian back. Don't merge me yet.
> Add russian.

- src/commands/runScripts/start-dev.js
After a `yarn run start:full` or `yarn run start`, if you encounter a build error in the WDS, we don't attempt to kill the process. However, if it's the first build, we kill all child processes and the main node process as well.
This works great in the HMR case. However, If you have an error on the first build, it works but with a weird side-effect:
```sadaf: ~/git_repo/mup-web [feature/upgrade_mwp_cli_may13] [!] $ yarn run start
yarn run v1.6.0
$ mope run
NODE_ENV=development
>> start-dev: Preparing the Dev App Server using existing vendor bundle...
(node:41424) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
>> ./src/assets/scss/main.scss (./node_modules/file-loader/dist/cjs.js?name=[name].[hash:7].css!./node_modules/extract-loader/lib/extractLoader.js!. …
```
> Fix HMR - Kill child process only on first build

- CHANGELOG.md
- Makefile
- docs/build.md
- src/commands/buildCommands/status.js
The markdown docs say it all https://github.com/meetup/mwp-cli/blob/f2167f593c4d0351ea316fed5455c1b4856996fd/docs/build.md#synopsis-build-status
> WP 648 `build status` with auto-cancel

- src/commands/buildCommands/configs/rules.js
one character change (hash length from 7 to 8 chars), SV
> standardize hash length for css

- src/commands/deployCommands/create.js
Currently the errorMessage could be:
- `Error: 4213-0 already deployed`
- `Error: The following quotas were exceeded: CPUS (quota: 256, used: 256 + needed: 2).`
- Nothing, https://travis-ci.com/meetup/pro-web/jobs/172741859#L706
Any already deployed is good one, the other error code should all stop the process from proceeding further.
> Refine exitCode for parent process flow

- Makefile
- package.json
- src/commands/buildCommands/configs/browserAppConfig.js
- src/commands/buildCommands/configs/rules.js
- src/commands/buildCommands/configs/serverAppConfig.js
This adds support for external css files in the `@meetup` scope on npm.
> support whitelisted external css

- src/commands/buildCommands/trn.js
> Revert "OS-90: Date picker calendar not localized"

- package.json
Updated `mwp-config` version in peer dependencies to match recently released https://github.com/meetup/meetup-web-platform/releases/tag/21.0.2897
> OS-449 Update mwp-config version

- src/commands/buildCommands/configs/rules.js
Add rules to load ts/tsx files from local packages
> Package source maps set up

- src/commands/buildCommands/configs/browserAppConfig.js
> Reduce memory usage: Remove hash from chunk names in dev

- CHANGELOG.md
- Makefile
- package.json
- src/commands/buildCommands/configs/rules.js
- yarn.lock
Waiting for: https://github.com/meetup/meetup-web-platform/pull/625
> Add packages path from mwp-config

- src/commands/buildCommands/pull.js
Added some more logging to make it easier to debug `mope build pull` commands
Related ticket: https://www.pivotaltracker.com/story/show/167746412
> Added some more logging to make it easier to debug mope build pull

- src/commands/build.js
- src/commands/bundle.js
- src/commands/bundleCommands/browser.js
- src/commands/bundleCommands/configs/browserAppConfig.js
- src/commands/bundleCommands/configs/postCssLoaderConfig.js
- src/commands/bundleCommands/configs/prodPlugins.js
- src/commands/bundleCommands/configs/rules.js
- src/commands/bundleCommands/configs/serverAppConfig.js
- src/commands/bundleCommands/configs/vendorBundlesConfig.js
- src/commands/bundleCommands/pull.js
- src/commands/bundleCommands/report.js
- src/commands/bundleCommands/server.js
- src/commands/bundleCommands/status.js
- src/commands/bundleCommands/trn.js
- src/commands/bundleCommands/vendor.js
- src/commands/runScripts/_webpack-dev-server.js
- src/commands/runScripts/start-dev.js
This is a prelim, in-progress PR for the `mupweb-app` monorepo work. 
The intent of this branch is to introduce NO BREAKING CHANGES, so that `pro-web` can continue to work without any necessary code changes. Eventually, `pro-web` will update and then we can retire the legacy build code.
Reference `mwp-config` branch: https://github.com/meetup/meetup-web-platform/pull/635
> ❗️MUPWEB-MONOREPO ❗️

- .huskyrc.js
- package.json
- src/cli.js
- src/commands/buildCommands/browser.js
- src/commands/buildCommands/configs/browserAppConfig.js
- src/commands/buildCommands/configs/prodPlugins.js
- src/commands/buildCommands/configs/rules.js
- src/commands/buildCommands/configs/serverAppConfig.js
- src/commands/buildCommands/pull.js
- src/commands/buildCommands/server.js
- src/commands/buildCommands/status.js
- src/commands/buildCommands/vendor.js
- src/commands/buildUtils/util.js
- src/commands/bundleCommands/browser.js
- src/commands/bundleCommands/configs/prodPlugins.js
- src/commands/bundleCommands/server.js
- src/commands/bundleCommands/status.js
- src/commands/bundleCommands/vendor.js
- src/commands/gh.js
- src/commands/ghCommands/status.js
- src/commands/run.js
- src/commands/runScripts/start-dev.js
- src/commands/txCommands/pullAll.js
- src/commands/txCommands/util/transifex.js
- src/util/addBabelOption.js
- yarn.lock
`lint-staged` wasn't running, so I fixed that.
The code changes are all prettier + eslint
> dependency updates

- .github/workflows/ci.yml
relates to meetup/meetup-web-platform#687
> chore(deps): bump node to 10.20.1
